/*
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.otus.social_network.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.time.LocalDate;
import java.util.Objects;

/**
 * UserRegisterPostRequest
 */
@JsonPropertyOrder({
  UserRegisterPostRequest.JSON_PROPERTY_FIRST_NAME,
  UserRegisterPostRequest.JSON_PROPERTY_SECOND_NAME,
  UserRegisterPostRequest.JSON_PROPERTY_BIRTHDATE,
  UserRegisterPostRequest.JSON_PROPERTY_BIOGRAPHY,
  UserRegisterPostRequest.JSON_PROPERTY_CITY,
  UserRegisterPostRequest.JSON_PROPERTY_PASSWORD
})
@JsonTypeName("_user_register_post_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-29T19:14:42.241620900+03:00[Europe/Moscow]", comments = "Generator version: 7.11.0")
public class UserRegisterPostRequest {
  public static final String JSON_PROPERTY_FIRST_NAME = "first_name";
  @jakarta.annotation.Nullable
  private String firstName;

  public static final String JSON_PROPERTY_SECOND_NAME = "second_name";
  @jakarta.annotation.Nullable
  private String secondName;

  public static final String JSON_PROPERTY_BIRTHDATE = "birthdate";
  @jakarta.annotation.Nullable
  private LocalDate birthdate;

  public static final String JSON_PROPERTY_BIOGRAPHY = "biography";
  @jakarta.annotation.Nullable
  private String biography;

  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @jakarta.annotation.Nullable
  private String password;

  public UserRegisterPostRequest() {
  }

  public UserRegisterPostRequest firstName(@jakarta.annotation.Nullable String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(@jakarta.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }

  public UserRegisterPostRequest secondName(@jakarta.annotation.Nullable String secondName) {
    
    this.secondName = secondName;
    return this;
  }

  /**
   * Get secondName
   * @return secondName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECOND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecondName() {
    return secondName;
  }


  @JsonProperty(JSON_PROPERTY_SECOND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondName(@jakarta.annotation.Nullable String secondName) {
    this.secondName = secondName;
  }

  public UserRegisterPostRequest birthdate(@jakarta.annotation.Nullable LocalDate birthdate) {
    
    this.birthdate = birthdate;
    return this;
  }

  /**
   * Дата рождения
   * @return birthdate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIRTHDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getBirthdate() {
    return birthdate;
  }


  @JsonProperty(JSON_PROPERTY_BIRTHDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBirthdate(@jakarta.annotation.Nullable LocalDate birthdate) {
    this.birthdate = birthdate;
  }

  public UserRegisterPostRequest biography(@jakarta.annotation.Nullable String biography) {
    
    this.biography = biography;
    return this;
  }

  /**
   * Get biography
   * @return biography
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIOGRAPHY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBiography() {
    return biography;
  }


  @JsonProperty(JSON_PROPERTY_BIOGRAPHY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBiography(@jakarta.annotation.Nullable String biography) {
    this.biography = biography;
  }

  public UserRegisterPostRequest city(@jakarta.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }

  public UserRegisterPostRequest password(@jakarta.annotation.Nullable String password) {
    
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@jakarta.annotation.Nullable String password) {
    this.password = password;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRegisterPostRequest userRegisterPostRequest = (UserRegisterPostRequest) o;
    return Objects.equals(this.firstName, userRegisterPostRequest.firstName) &&
        Objects.equals(this.secondName, userRegisterPostRequest.secondName) &&
        Objects.equals(this.birthdate, userRegisterPostRequest.birthdate) &&
        Objects.equals(this.biography, userRegisterPostRequest.biography) &&
        Objects.equals(this.city, userRegisterPostRequest.city) &&
        Objects.equals(this.password, userRegisterPostRequest.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, secondName, birthdate, biography, city, password);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRegisterPostRequest {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    secondName: ").append(toIndentedString(secondName)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    biography: ").append(toIndentedString(biography)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

